def dataConversation():
    conversation = [
	"Hello.",
	"Hi.",
	"How are you?",
	"I'm good. How are you?",
	"Good. Do you speak English?",
	"A little. Are you VietNam?",
	"Yes.",
	"Where are you from?",
	"I'm from VietNam.",
	"Nice to meet you.",
	"Nice to meet you too.",
	"Hello",
   	"Hi there!",
    	"How are you doing?",
   	"I'm doing great.",
    	"That is good to hear",
    	"Thank you.",
    	"You're welcome.",
	"Excuse me, are you Chatbot?",
	"Yes, I am a Chatbot",
	"Do you speak English?",
	"A little, but not very well.",
	"How long have you been here?",
	"2 months.",
	"What do you do for work?",
	"I'm a student. How about you?",
	"I'm a student too.",
	"what are you going to do today?",
	"I'm going shopping.",
	"Will you buy a ham sandwich for me at the store?",
	"OK",
	"Do you have enough money?",
	"I'm not sure",
	"How much do you have?",
	"25 dollars. Do you think that's enough?",
	"That's not very much",
	"I think it's OK. I also have two credit cards",
	"Let me give you another ten dollars",
	"Thanks. See you later",
	"Bye.",
	"Good morning! How are you doing?",
	"I am doing very well, thank you for asking.",
	"You're welcome.",
	"Do you like hats?",
	"How are you?",
    	"I am good.",
    	"That is good to hear.",
   	"Thank you",
    	"You are welcome.",
	"Greetings!",
    	"Hello",
 ]
   return conversation


