def dataConversation():
    conversation = [
	"Hello.",
	"Hi.",
	"How are you?",
	"I'm good. How are you?",
	"Good. Do you speak English?",
	"A little. Are you VietNam?",
	"Yes.",
	"Where are you from?",
	"I'm from VietNam.",
	"Nice to meet you.",
	"Nice to meet you too.",
	"Hello",
   	"Hi there!",
    "How are you doing?",
   	"I'm doing great.",
    "That is good to hear",
    "Thank you.",
    "You're welcome.",
	"Excuse me, are you Chatbot?",
	"Yes, I am a Chatbot",
	"Do you speak English?",
	"A little, but not very well.",
	"How long have you been here?",
	"2 months.",
	"What do you do for work?",
	"I'm a student. How about you?",
	"I'm a student too.",
	"what are you going to do today?",
	"I'm going shopping.",
	"Will you buy a ham sandwich for me at the store?",
	"OK",
	"Do you have enough money?",
	"I'm not sure",
	"How much do you have?",
	"25 dollars. Do you think that's enough?",
	"That's not very much",
	"I think it's OK. I also have two credit cards",
	"Let me give you another ten dollars",
	"Thanks. See you later",
	"Bye.",
	"Good morning! How are you doing?",
	"I am doing very well, thank you for asking.",
	"You're welcome.",
	"Do you like hats?",
	"How are you?",
    "I am good.",
    "That is good to hear.",
   	"Thank you",
    "You are welcome.",
	"Greetings!",
    "Hello",
	"Hello,good morning ",
	"Hi,good morning",
	"How are you? ",
	"I'm fine thank you",
	"How are you?",
	"Now that you’re here, I feel great. ",
	"Lol, really?",
	"What’s wrong? ",
	"I’m breaking up with my lover.",
	"I’m really sorry!",
	"That’s ok, I’ll be fine",
	"I’m bored.",
	" What’s on TV?",
	"Nothing. ",
	"There must be something on TV!",
	"Nothing that’s interesting.",
	"What about that new game show?",
	"Which one?",
	"Do you have a girlfriend?",
	"No, I don’t. Do you? ",
	"I don’t have a girlfriend, either",
	"Why not?",
	"I don’t know. Maybe I’m not rich enough.",
	"Girls like guys with money.",
	"They sure do",
	"They like guys with new cars.",
	"I don’t have money or a new car",
	"Me, neither.",
	"But girls like guys who are funny.",
	"Maybe we should learn some good jokes.",
	"Where’s the counter?",
	"I don’t know. Let’s go to Information",
	"Where’s the counter, please?",
	"It’s over here, next to gate 8",
	"Good morning, we would like to check in",
	"Good morning, let me have your plane tickets, please",
	"Could we have a window seat, please?",
	"Of course, no problem. Smoking or non-smoking?",
	"Non-smoking, please. Which gate are we boarding from?",
	"Gate 6",
	"Thank you",
	"How has your day been so far?",
	"Hey there. You look like you’re having a rough day",
 ]
   return conversation


